build-AuthorizerLambda:
	cp -r ./bundle $(ARTIFACTS_DIR)/bundle

build-ApiLambda:
	cp -r ./bundle $(ARTIFACTS_DIR)/bundle

build-LightfunnelsLambda:
	cp -r ./bundle $(ARTIFACTS_DIR)/bundle
	
build-WebhooksLambda:
	cp -r ./bundle $(ARTIFACTS_DIR)/bundle

build-Layer:
	mkdir -p $(ARTIFACTS_DIR)/nodejs
	cp -r ./node_modules $(ARTIFACTS_DIR)/nodejs/node_modules
	cp ./package.json $(ARTIFACTS_DIR)/nodejs/package.json